#!/usr/bin/env bash
# install and setup haproxy on a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 83170-web-52.91.127.220 check
    server 83170-web-54.144.22.15 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
